### ISSUE TITLE
New Viewing Party Page

### ISSUE THREAD

**Issue by iandouglas** [rrabinovitch/viewing_party#7]
As an authenticated user,
When I visit the new viewing party page,
I should see a form with the following:
- [x] Movie Title (that is un-editable)
- [x] Duration of Party with a default value of movie runtime in minutes
- [x] When: as a date picker
- [x] Checkboxes next to each friend (if user has friends)
- [x]  Button to create party

**Comment by rrabinovitch** [comment]
using [this](https://apidock.com/rails/ActionView/Helpers/FormTagHelper/check_box_tag#64-Pass-id-collections-with-check-box-tags) recommendation for checkbox field syntax. what purpose does the `h` in `h friend.username` serve?

**Comment by rrabinovitch** [comment]
we don't currently have a name saved for each user, just a username - we can decide later if we want to edit this so that a new viewing party form can have you select a user's name instead of just their email username

**Comment by iandouglas** [comment]
the `h` reference here is an alias for escaping HTML characters. This is to protect your application from someone who may have injected something in your database like a username of `John<script>alert("ian was here, mwuahahaha");</script> Smith` ... the `h` here would ensure that those characters are shown as-is, instead of being interpreted as html or executed as javascript. Think of it as the opposite of `html_safe` where you're saying "I trust the content in this field, go ahead and interpret it as html/javascript if needed"

**Comment by rrabinovitch** [comment]
Ahh, noted/good to know - thank you for the explanation, @iandouglas !
